# Generated by Django 3.2 on 2023-09-12 11:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_systeminfo_paymentapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='departureDate',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
