# Generated by Django 4.0.3 on 2023-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.FloatField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
